# Generated by Django 5.2.7 on 2025-11-09 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('block_type', models.CharField(max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('input_shape', models.JSONField(blank=True, null=True)),
                ('output_shape', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelArchitecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_state', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('framework', models.CharField(choices=[('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow')], default='pytorch', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.CharField(max_length=255)),
                ('source_handle', models.CharField(blank=True, default='', max_length=50)),
                ('target_handle', models.CharField(blank=True, default='', max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='block_manager.block')),
                ('target_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='block_manager.block')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='block_manager.modelarchitecture')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='architecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='block_manager.modelarchitecture'),
        ),
        migrations.AddField(
            model_name='modelarchitecture',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='block_manager.project'),
        ),
    ]
