# Generated by Django 5.2.8 on 2025-12-05 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='repetition_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupBlockDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='utility', max_length=50)),
                ('color', models.CharField(default='#9333ea', max_length=50)),
                ('internal_structure', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_definitions', to='block_manager.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='block',
            name='group_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='block_manager.groupblockdefinition'),
        ),
    ]
