# Generated by Django 5.2.8 on 2025-12-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_manager', '0002_block_is_expanded_block_repetition_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='instance_config_overrides',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
