# Generated by Django 5.2.8 on 2025-12-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('block_manager', '0003_add_instance_config_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.user'),
        ),
    ]
