# Generated by Django 5.2.8 on 2026-02-23 04:37

import block_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_manager', '0005_project_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='config',
            field=models.JSONField(blank=True, default=dict, validators=[block_manager.validators.validate_block_config]),
        ),
        migrations.AlterField(
            model_name='block',
            name='input_shape',
            field=models.JSONField(blank=True, null=True, validators=[block_manager.validators.validate_shape_data]),
        ),
        migrations.AlterField(
            model_name='block',
            name='output_shape',
            field=models.JSONField(blank=True, null=True, validators=[block_manager.validators.validate_shape_data]),
        ),
        migrations.AlterField(
            model_name='groupblockdefinition',
            name='internal_structure',
            field=models.JSONField(blank=True, default=dict, validators=[block_manager.validators.validate_group_internal_structure]),
        ),
        migrations.AlterField(
            model_name='modelarchitecture',
            name='canvas_state',
            field=models.JSONField(blank=True, default=dict, validators=[block_manager.validators.validate_canvas_state]),
        ),
    ]
