# Generated by Django 5.2.8 on 2025-12-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firebase_uid', models.CharField(help_text='Firebase user ID (primary key)', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='User email from Firebase', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name from OAuth provider', max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, help_text='Profile photo URL from OAuth provider', null=True)),
                ('auth_provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], help_text='OAuth provider used for authentication', max_length=20)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', help_text='User subscription tier', max_length=10)),
                ('project_count', models.IntegerField(default=0, help_text='Number of projects created by user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of user sessions')),
                ('total_time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent in app (minutes)')),
                ('first_model_created_at', models.DateTimeField(blank=True, help_text='Timestamp of first model creation', null=True)),
                ('first_export_at', models.DateTimeField(blank=True, help_text='Timestamp of first export', null=True)),
                ('days_to_first_export', models.IntegerField(blank=True, help_text='Days from signup to first export', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
