"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

load_dotenv()  # take environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable must be set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Environment Variable Validation (Production Only)
REQUIRED_ENV_VARS = [
    'DJANGO_SECRET_KEY',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_PRIVATE_KEY',
    'FIREBASE_CLIENT_EMAIL',
    'ORACLE_USER',
    'ORACLE_PASSWORD',
    'ORACLE_DSN',
]

# Validate required environment variables in production
if not DEBUG:
    missing = [var for var in REQUIRED_ENV_VARS if not os.getenv(var)]
    if missing:
        print("=" * 70)
        print("ERROR: Missing required environment variables for production")
        print("=" * 70)
        print(f"Missing variables: {', '.join(missing)}")
        print("\nPlease check your .env file and ensure all required variables are set.")
        print("See project/.env.example for reference.")
        print("=" * 70)
        sys.exit(1)

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'block_manager',
    'authentication',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.FirebaseAuthenticationMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# Disable automatic slash appending for API endpoints
APPEND_SLASH = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# CORS configuration - read from environment variable for production
if DEBUG:
    cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173,http://localhost:5000')
else:
    cors_origins = os.getenv('CORS_ALLOWED_ORIGINS')
    if not cors_origins:
        raise ValueError("CORS_ALLOWED_ORIGINS environment variable must be set in production")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-gemini-api-key',
    'x-anthropic-api-key',
    'x-firebase-token',
]

if DEBUG:
    csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://localhost:5173,http://localhost:5000')
else:
    csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
    if not csrf_origins:
        raise ValueError("CSRF_TRUSTED_ORIGINS environment variable must be set in production")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(',')]

# CSRF Protection
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# Environment mode configuration
# Controls API key behavior: PROD/missing = BYOK, DEV/LOCAL = server keys
ENVIRONMENT = os.getenv('ENVIRONMENT', 'DEV')
IS_PRODUCTION = ENVIRONMENT == 'PROD'
REQUIRES_USER_API_KEY = IS_PRODUCTION

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/hour",
        "user": "600/hour",
    },
}

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # Oracle Autonomous Database - now default for all data
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': os.getenv('ORACLE_DSN', ''),
        'USER': os.getenv('ORACLE_USER', ''),
        'PASSWORD': os.getenv('ORACLE_PASSWORD', ''),
        'OPTIONS': {
            'config_dir': os.getenv('ORACLE_WALLET_LOCATION', ''),
            'wallet_location': os.getenv('ORACLE_WALLET_LOCATION', ''),
            'wallet_password': os.getenv('ORACLE_WALLET_PASSWORD', ''),
        },
    },
    # SQLite kept as backup/reference only
    'sqlite_backup': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# Database Router - REMOVED (all data now in Oracle)

# Firebase Configuration
FIREBASE_CONFIG = {
    'apiKey': os.getenv('FIREBASE_API_KEY', ''),
    'authDomain': os.getenv('FIREBASE_AUTH_DOMAIN', ''),
    'projectId': os.getenv('FIREBASE_PROJECT_ID', ''),
    'storageBucket': os.getenv('FIREBASE_STORAGE_BUCKET', ''),
    'messagingSenderId': os.getenv('FIREBASE_MESSAGING_SENDER_ID', ''),
    'appId': os.getenv('FIREBASE_APP_ID', ''),
    'measurementId': os.getenv('FIREBASE_MEASUREMENT_ID', ''),
}

# Oracle Wallet Location (for cloud database connection)
ORACLE_WALLET_LOCATION = os.getenv('ORACLE_WALLET_LOCATION', '')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==========================================
# SECURITY HEADERS (Production Only)
# ==========================================
if not DEBUG:
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = True

    # Session and CSRF cookies only over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Prevent clickjacking
    X_FRAME_OPTIONS = 'DENY'

    # Prevent MIME type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Enable XSS filter in browsers
    SECURE_BROWSER_XSS_FILTER = True

    # Referrer policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

    # Cross-Origin-Opener-Policy - Required for Firebase popup authentication
    # https://github.com/firebase/firebase-js-sdk/issues/8541
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

    # Content Security Policy
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://www.gstatic.com", "https://apis.google.com")
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")
    CSP_IMG_SRC = ("'self'", "data:", "https:", "blob:")
    CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "data:")
    CSP_CONNECT_SRC = ("'self'", "https://firebasestorage.googleapis.com", "https://identitytoolkit.googleapis.com", "https://securetoken.googleapis.com", "https://*.googleapis.com")
    CSP_FRAME_SRC = ("https://accounts.google.com", "https://github.com")
    CSP_OBJECT_SRC = ("'none'",)
    CSP_BASE_URI = ("'self'",)

else:
    # Development settings - less strict
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/assets/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist' / 'assets',
    BASE_DIR / 'frontend' / 'dist',  # Also collect logo, video, and other root assets
]

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True
# Serve root-level assets (logo, video, etc.) at root URL
# These files are moved to dist/root/ by build script
WHITENOISE_ROOT = BASE_DIR / 'frontend' / 'dist' / 'root'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
