"""
VisionForge CLI

Command-line interface for VisionForge local application.
"""

import os
import sys
import argparse
import webbrowser
from pathlib import Path
from typing import Optional


def init_command():
    """Initialize VisionForge configuration"""
    print("🔧 Initializing VisionForge configuration...\n")

    env_path = Path.cwd() / ".env"

    if env_path.exists():
        print("⚠️  .env file already exists in this directory")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != "y":
            print("❌ Initialization cancelled")
            return

    print("VisionForge can work completely offline without AI features.")
    print("To enable AI-powered assistance, you can optionally add API keys.\n")
    print("Available AI providers:")
    print("  • Google Gemini (https://aistudio.google.com/app/apikey)")
    print("  • Anthropic Claude (https://console.anthropic.com/)\n")
    print("Press Enter to skip if you don't want AI features.\n")

    # Get optional API keys
    gemini_key = input("Gemini API key (optional): ").strip()
    anthropic_key = input("Anthropic API key (optional): ").strip()

    # Get server configuration
    print("\nServer configuration (press Enter for defaults):")
    host = input("Host [127.0.0.1]: ").strip() or "127.0.0.1"
    port = input("Port [8000]: ").strip() or "8000"

    # Validate port
    try:
        port_int = int(port)
        if not (1024 <= port_int <= 65535):
            raise ValueError
    except ValueError:
        print("⚠️  Invalid port number, using default: 8000")
        port = "8000"

    # Write .env file
    with open(env_path, "w") as f:
        f.write("# VisionForge Configuration\n")
        f.write("# Generated by vision-forge init\n\n")

        f.write("# Server Configuration\n")
        f.write(f"HOST={host}\n")
        f.write(f"PORT={port}\n\n")

        f.write("# AI Features (Optional)\n")
        f.write("# Leave empty to use VisionForge without AI assistance\n")
        if gemini_key:
            f.write(f"GEMINI_API_KEY={gemini_key}\n")
        else:
            f.write("# GEMINI_API_KEY=your_gemini_key_here\n")

        if anthropic_key:
            f.write(f"ANTHROPIC_API_KEY={anthropic_key}\n")
        else:
            f.write("# ANTHROPIC_API_KEY=your_anthropic_key_here\n")

    print(f"\n✅ Configuration saved to {env_path}")
    print("\n🚀 You can now run 'vision-forge start' to launch the application!")

    if not gemini_key and not anthropic_key:
        print("\n💡 Tip: You can add API keys later by editing .env file")


def start_command(host: Optional[str] = None, port: Optional[int] = None, open_browser: bool = True):
    """Start the VisionForge server"""
    import uvicorn
    from dotenv import load_dotenv
    from .server import create_app

    # Load environment variables
    load_dotenv()

    # Use CLI args if provided, otherwise use .env, otherwise use defaults
    server_host = host or os.getenv("HOST", "127.0.0.1")
    server_port = port or int(os.getenv("PORT", "8000"))

    # Check if .env exists
    env_path = Path.cwd() / ".env"
    if not env_path.exists():
        print("⚠️  No .env file found in current directory")
        print("Run 'vision-forge init' first to create configuration\n")
        response = input("Continue anyway with defaults? (y/N): ").strip().lower()
        if response != "y":
            print("❌ Startup cancelled")
            return

    # Check AI configuration
    gemini_key = os.getenv("GEMINI_API_KEY")
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    ai_enabled = bool(gemini_key or anthropic_key)

    # Create the app
    app = create_app()

    # Print startup banner
    print("\n" + "=" * 60)
    print("🎨 VisionForge - Visual Neural Network Builder")
    print("=" * 60)
    print(f"\n📍 Server:      http://{server_host}:{server_port}")
    print(f"🤖 AI Features: {'✅ Enabled' if ai_enabled else '❌ Disabled'}")
    if not ai_enabled:
        print("   💡 Add API keys to .env to enable AI features")
    print("\n🛑 Press Ctrl+C to stop the server")
    print("=" * 60 + "\n")

    # Open browser
    if open_browser:
        url = f"http://{server_host}:{server_port}"
        print(f"🌐 Opening {url} in your browser...\n")
        webbrowser.open(url)

    # Start server
    try:
        uvicorn.run(app, host=server_host, port=server_port, log_level="info")
    except KeyboardInterrupt:
        print("\n\n👋 VisionForge stopped. Goodbye!")
    except Exception as e:
        print(f"\n❌ Error starting server: {e}")
        sys.exit(1)


def version_command():
    """Show version information"""
    from . import __version__
    print(f"VisionForge version {__version__}")


def main():
    """Main CLI entry point"""
    parser = argparse.ArgumentParser(
        description="VisionForge - Visual Neural Network Builder",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  vision-forge init                    Initialize configuration
  vision-forge start                   Start the application
  vision-forge start --port 3000       Start on custom port
  vision-forge start --no-browser      Start without opening browser
  vision-forge --version               Show version
        """
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s 0.1.0"
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Init command
    init_parser = subparsers.add_parser("init", help="Initialize VisionForge configuration")

    # Start command
    start_parser = subparsers.add_parser("start", help="Start VisionForge server")
    start_parser.add_argument(
        "--host",
        type=str,
        default=None,
        help="Server host (default: 127.0.0.1)"
    )
    start_parser.add_argument(
        "--port",
        type=int,
        default=None,
        help="Server port (default: 8000)"
    )
    start_parser.add_argument(
        "--no-browser",
        action="store_true",
        help="Don't open browser automatically"
    )

    args = parser.parse_args()

    # Execute command
    if args.command == "init":
        init_command()
    elif args.command == "start":
        start_command(
            host=args.host,
            port=args.port,
            open_browser=not args.no_browser
        )
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
